/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_devices_NativeInputAudioDevice */

#ifndef _Included_org_plovdev_audioengine_devices_NativeInputAudioDevice
#define _Included_org_plovdev_audioengine_devices_NativeInputAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_devices_NativeInputAudioDevice
 * Method:    _open
 * Signature: (Lorg/plovdev/audioengine/tracks/format/TrackFormat;Lorg/plovdev/audioengine/devices/AudioDeviceInfo;)V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeInputAudioDevice__1open
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeInputAudioDevice
 * Method:    _read
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_plovdev_audioengine_devices_NativeInputAudioDevice__1read
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeInputAudioDevice
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeInputAudioDevice__1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
