/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_devices_AudioDeviceManager */

#ifndef _Included_org_plovdev_audioengine_devices_AudioDeviceManager
#define _Included_org_plovdev_audioengine_devices_AudioDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_devices_AudioDeviceManager
 * Method:    _getDefaultInputAudioDevice
 * Signature: ()Lorg/plovdev/audioengine/devices/AudioDeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_devices_AudioDeviceManager__1getDefaultInputAudioDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_AudioDeviceManager
 * Method:    _getDefaultOutputAudioDevice
 * Signature: ()Lorg/plovdev/audioengine/devices/AudioDeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_devices_AudioDeviceManager__1getDefaultOutputAudioDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_AudioDeviceManager
 * Method:    _getInputAudioDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_devices_AudioDeviceManager__1getInputAudioDevices
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_AudioDeviceManager
 * Method:    _getOutputAudioDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_devices_AudioDeviceManager__1getOutputAudioDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
