/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_devices_NativeOutputAudioDevice */

#ifndef _Included_org_plovdev_audioengine_devices_NativeOutputAudioDevice
#define _Included_org_plovdev_audioengine_devices_NativeOutputAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _open
 * Signature: (Lorg/plovdev/audioengine/format/TrackFormat;Lorg/plovdev/audioengine/devices/AudioDeviceInfo;)J
 */
JNIEXPORT jlong JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1open
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _write
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1write__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _write
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1write__JJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
