/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_devices_NativeOutputAudioDevice */

#ifndef _Included_org_plovdev_audioengine_devices_NativeOutputAudioDevice
#define _Included_org_plovdev_audioengine_devices_NativeOutputAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _setProvider
 * Signature: (Lorg/plovdev/audioengine/devices/ChunkProvider;)V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1setProvider
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _open
 * Signature: (Ljava/lang/String;Lorg/plovdev/audioengine/tracks/format/TrackFormat;)V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1open
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _write
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1write
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1flush
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _close
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1close
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_plovdev_audioengine_devices_NativeOutputAudioDevice
 * Method:    _onNextChunkRequired
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_NativeOutputAudioDevice__1onNextChunkRequired
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
