/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_NativeAudioEngine */

#ifndef _Included_org_plovdev_audioengine_NativeAudioEngine
#define _Included_org_plovdev_audioengine_NativeAudioEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_NativeAudioEngine
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_NativeAudioEngine__1init
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_NativeAudioEngine
 * Method:    _cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_NativeAudioEngine__1cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
