/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_devices_Microphone */

#ifndef _Included_org_plovdev_audioengine_devices_Microphone
#define _Included_org_plovdev_audioengine_devices_Microphone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_devices_Microphone
 * Method:    _start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_Microphone__1start
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_Microphone
 * Method:    _stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_Microphone__1stop
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_Microphone
 * Method:    _getReadedData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_devices_Microphone__1getReadedData
  (JNIEnv *, jobject);

/*
 * Class:     org_plovdev_audioengine_devices_Microphone
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_plovdev_audioengine_devices_Microphone__1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
