package org.plovdev.audioengine.generator.config;

/**
 * Defines the shape of the waveform generated by the audio engine.
 * <p>
 * Each wave type produces a distinct timbre and is suitable for different use cases:
 * <ul>
 *   <li>Basic waveforms for subtractive synthesis (SINE, SQUARE, SAWTOOTH, TRIANGLE)</li>
 *   <li>Noise generators for percussion and effects (NOISE)</li>
 *   <li>Test signals for measurement and debugging (IMPULSE, SILENCE)</li>
 *   <li>Swept signals for frequency response testing (CHIRP, SWEEP)</li>
 * </ul>
 * </p>
 */
public enum WaveType {

    /**
     * Pure sine wave.
     * <p>
     * Contains only the fundamental frequency with no harmonics.
     * Produces a clean, smooth tone.
     * Ideal for testing, bass sounds, and flute-like timbres.
     * </p>
     */
    SINE,

    /**
     * Square wave.
     * <p>
     * Contains odd-numbered harmonics at decreasing amplitudes.
     * Produces a hollow, reed-like sound.
     * Commonly used for chiptune music, synth basses, and wind instrument emulation.
     * </p>
     */
    SQUARE,

    /**
     * Sawtooth wave.
     * <p>
     * Contains both odd and even harmonics.
     * Produces a bright, buzzing sound.
     * Excellent for rich basses, string ensemble sounds, and pad textures.
     * </p>
     */
    SAWTOOTH,

    /**
     * Triangle wave.
     * <p>
     * Contains odd harmonics that roll off quickly.
     * Produces a soft, flute-like tone with fewer harsh overtones than square waves.
     * Useful for mellow leads, sub-basses, and bell-like tones.
     * </p>
     */
    TRIANGLE,

    /**
     * White noise.
     * <p>
     * Random signal with equal energy across all frequencies.
     * Generates a "shhh" sound.
     * Perfect for snare drums, cymbals, wind effects, and percussive sounds.
     * </p>
     */
    NOISE,

    /**
     * Dirac impulse.
     * <p>
     * A single sample with maximum amplitude followed by zeros.
     * Contains all frequencies at equal energy.
     * Used for impulse response measurements, system testing, and click tracks.
     * </p>
     */
    IMPULSE,

    /**
     * Silence (no signal).
     * <p>
     * Generates a track with all samples set to zero.
     * Useful for creating pauses, separators between sounds, or placeholders.
     * </p>
     */
    SILENCE,

    /**
     * Linear frequency sweep (chirp).
     * <p>
     * Frequency changes linearly from start to end over the duration.
     * Example: 400Hz → 2000Hz linearly.
     * Ideal for testing frequency response of audio systems.
     * </p>
     */
    CHIRP,

    /**
     * Exponential frequency sweep.
     * <p>
     * Frequency changes exponentially (logarithmically) from start to end.
     * Example: 400Hz → 2000Hz with exponential curve.
     * Better matches human pitch perception.
     * </p>
     */
    SWEEP
}