/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_plovdev_audioengine_mixer_NativeTrackMixer */

#ifndef _Included_org_plovdev_audioengine_mixer_NativeTrackMixer
#define _Included_org_plovdev_audioengine_mixer_NativeTrackMixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_plovdev_audioengine_mixer_NativeTrackMixer
 * Method:    _doMixing
 * Signature: (Ljava/util/List;Lorg/plovdev/audioengine/tracks/format/TrackFormat;)Lorg/plovdev/audioengine/tracks/Track;
 */
JNIEXPORT jobject JNICALL Java_org_plovdev_audioengine_mixer_NativeTrackMixer__1doMixing
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
